# gce-instance-resource task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: gce-instance-resource

outputs:
- name: gce-instance-resource-updated

run:
  path: ./gce-instance-resource/ci/scripts/readme-github-pages.sh
