platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.3

inputs:
- name: gce-instance-resource

outputs:
- name: dist

run:
  path: ./gce-instance-resource/ci/scripts/build-push.sh
