platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: gce-instance-resource

outputs:
- name: coverage-results

run:
  path: ./gce-instance-resource/ci/scripts/unit-tests.sh