# gce-instance-resource .credentials.yml

slack_url: https://hooks.slack.com/services/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
repo_github_token: c31b961ebbd1c65f3182be4eed4c4ea3cf3d9668
dockerhub_password: dcot1968dD.
git_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJJwIBAAKCAgEAv2hszcQH9NaTQUtPaMc11pFAXNfbmJ57vKrgz7g6QJfl/0Tq
    OOlDutuzRCcVjVIIzsHqeEZQ9iGdZZ4Co5+jizzA1EG4S/kSvQwNUt+oBKAQWk31
    nehzc3wQHbmyS90h8NDd1iCOyRAlroeKYwSl9mF6yxWpF066p/IIZrovrJsxKDVW
    Zz5SWNtmcT57knLTijGqNX92cjyityAIn9JJhH+1ltlbCS2EZEsxEZVzHP/gPs5o
    VCIh8OJEQbDYbZijR7O9Xj2YVHc8tIs9UYUrEcZmAt2J1GtFzbVirRO3go3fH69r
    pv6SuDjWNSBEclMhM1eX7KS2+XpbLrtsuQrJgVvb3G7+jf4fFYC2U37Uzga4e1c+
    kskMP32yth/z3p1IWf15kk1a3nEt+tS9ozMeCdcIUoGhv/mouBf49iopjT1bcsZX
    TAB9vdtieho53dT0WmNKNCbMezBzkOePDaJd9mLUc6/YVD40OpXSToi5OP6+Lb4x
    6S0o4/5xZNd71LVqAF/5+pBq3LX7yNYhxDvtaLbp0FKKLgc8K0/XJ9edsCCvTnQj
    8HdsC5o520Ivg2pckT2HV2SqYjkQJFAVmOYmmRumoa5A0eUqqHNwr5lSLMiHz9pX
    i9OTCmXXjXCgfDiNBwux6nwdCJSFZcLZfYIGC/bneJbYdi+ey5sa27+Wz20CAwEA
    AQKCAgBL0amHuGcObRDXhGVoM8D3xYGhRUAPLHgHPAjhPzCT9Zd9jmbZNE1H708L
    aA/5cs1aWSXvjqrzVE1suzKAbfPya5ZWfdHrBjaN/AArG70KV/0iSE9KxZE15abc
    n3oo4udW5OV6tFra+jJy9+2xW14CQorJd0MLoHv/mrgJOSc5UCAgtUAMlXs5B2+E
    3CNG14VD8HhjyKG6jppFv8KqzDmi6pObtW2CLS2MLNy7AmAe1JyXRFu/N+YJ7Rbs
    joisoRHMjT4t3mhAzRqWybD4Ya+10skFyYuXQQbdfUQhGvZOGLSRcINMGvszThBL
    6wQx5Qv5snDTpEt2dyk3Uba3dbZrfvEc/N14gCAFPe1v6XkepnEmRjVBlsyfR3AS
    AeniifWAGn6BGnixosRr4Q8CtAw0pO1PqoPtvJ1mrjLAhidrWDVzYIT4yIyGdIke
    Ny1PYcPHYtU1S1fOjch+SJbbLkkK80Zb5T1QuzrB2Q46Z6XEmxtwJmO+n/Ge9IGV
    z4bAxh/HLiZrT9/0sMl/UStYnL9aj/JoNOPawJlTwO6ak0BtgzBlBcb5NNCfzbLN
    m+0ZPkknZwzAD2YwVp7xXyKIEvUA5bWSygwYAmbnOQ9OIZDGD1GdYo12zjM2I6MK
    b0Dye16VpFN6EpXXee3sxV/BE04zLfPA/KJ8ASRLOhjybs0CAQKCAQEA9xheeyiG
    gAj5epuiJgAD2bWjAvnB+mfRvZbEewPP7WzT3Ub1+7hFbZrG0/8eowqaLTpqIro9
    OPoHsdG4v3Ul/o19QtgkpQo3YFruoPZba+aoTFyfpuA5YJ3Xm6covqwSU5iEYOez
    5cH7MLYhYt3XWTEP8EjaxP7LHQ0o8buuVPmk3NcVQgMs6lT2ay7ogMsXcFqXi6sQ
    88hUc2bQ9RUNANA0drpCnPcTj1SOLwFt+MW/tDHR/IwEhvxp3sVk1JfAaL/AAJDk
    JLnnop4uOOfxanUoPwSix58lXQgVVDOa+dEwHybJRB9LixHMFapHEwN5TaK6n1+h
    yCYlMPF9sV5LsQKCAQEAxk5M+zo/DiKt1XsygGyS9Ov/x+M64AQQJWk+EdjmBTd9
    cqbwU+e+iCFgmdellnoQ545vMkuzB0Iulqgo5XWDQVI5JJZ+FRt+Q/fRho+7YOWH
    bGZwcPZWHEoMHvdl+46dVLlM1k3lIfo0eHAAwOASqybrxQlF6NUkkyBxsJy5ngwJ
    A1tyJI+PcWst+8P60B6JnEO40r501lnXZBt/VmT4mzK5NYsjhVDe0Gl9NfGudUX6
    eopi+DCr1Co2UeBYJXedWKqGfBN352xRvPTUrS+y4sUjRB8lC9qbXKjU8VFUdi7u
    U2fhpumFqHEWr4GrKVtW+p2BI2E8MD6zhsH53fH6fQKCAQBDV3PgctH9MPT1Eldl
    rdleyx7rH7BbE1JZLi7MK+TOGzu+cal2eekKDwWjH0N1Qd10+BeW8VTgI1xXfQWx
    wDajomICBrAt/pPLAd1JJvsRdCJn9VJZg4B/sWTiefMjy/eOquFhG6SuuGhCBVEi
    Bb28BCAI54If8CTg/QYso27Gn+brfP7BJ+Zk0tT5ryYUe8UejMICgZO0LOO/M8U9
    FgieMSArP2YKK1g8VtoNO4GCLDqr3GwTPQG63C3qVbe+LMF2itPEE7jpvXTAoAWO
    4r+ruNRIIHZQmzHuodZWRV42OWm5A7QUicbn1ujc+rQ2HVtA6lmcN876olK+fQI5
    ha5xAoIBAFso/Yxzzy7BVGYR1zpgLwI2RwPtelAmrgF0qtrreXomcx20jkAUBWtw
    5IZ0MqPFA2Ze/NEDKY6Jpv8M2Jf6+Fab5LbkE5vCYr39+yy/gCTf/uwe/0t+gkFI
    7N+DXTdR7RNYh3DwqAeBjINdAYuotgxFvRZ7185bxQ95V6oXseBsqewIKqWR9R/v
    ZFkbU34+u4XBQAJpGS68aB6V4Wimy/4USD3L841CitsF01BsBIXWoHmaijqLrUHA
    Ee57kinPHd73rRD2piUVj1GsvuPKTJKgi0CyjIYxfUAQQKuadphJpLdkxr/DE/VF
    32bY1gUR/x8ALrBD77ZB7KdjHmkf5sUCggEAGLmEkOD56YV7lQ8XerHIhwcT05ya
    XvLz8wKYfZzi60ipcyEteHXLpjtmihbYqKkpa6I7cwAO6FZzxobBs66ILsheksfA
    YYkEM9glqJ1n2qjydJ8UNvsths5mgmiLRelSLoPoKZJpuqEcZnRYixrW2YEXY8lR
    9RiBB0fV93DB4Yu+meZR1uCD0eGqae29TMFCu+GQ+Z1fcD12GBSA3d6BFEKlCxDm
    34LZuSipmdN+kBOi/bBs2VMEdVx4S5NfWOUPr0JDNrR6Tj0urAlc3eE21HzhZX+8
    SN6e1rH3ZYs+cTT/JlmqM70kvZj9GxwuiVvqn6GYniQe5IWy9CMdFu//bg==
    -----END RSA PRIVATE KEY-----
