# gce-instance-resource pipeline.yml

jobs:

- name: job-readme-github-pages
  plan:
  - get: gce-instance-resource
    trigger: true
  - put: resource-slack-alert
    params:
      channel: '#jeff-builds'
      text: "From gce-instance-resource: STARTED job-readme-github-pages in concourse ci."
  - put: resource-repo-status
    params: { state: "pending", description: "STARTED job-readme-github-pages in concourse ci.", commit: "gce-instance-resource" }
  - task: task-readme-github-pages
    file: gce-instance-resource/ci/tasks/task-readme-github-pages.yml
    on_success:
      do:
      - put: gce-instance-resource
        params:
          repository: gce-instance-resource-updated  
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From gce-instance-resource: PASSED job-readme-github-pages in concourse ci."
      - put: resource-repo-status
        params: { state: "success", description: "PASSED job-readme-github-pages in concourse ci", commit: "gce-instance-resource" }
    on_failure:
      do:
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From gce-instance-resource: FAILED job-readme-github-pages in concourse ci."
      - put: resource-repo-status
        params: { state: "failure", description: "FAILED job-readme-github-pages in concourse ci", commit: "gce-instance-resource" }

- name: job-unit-tests
  plan:
  - get: gce-instance-resource
    trigger: true
    passed: [job-readme-github-pages]
  - put: resource-slack-alert
    params:
      channel: '#jeff-builds'
      text: "From gce-instance-resource: STARTED job-unit-tests in concourse ci."
  - put: resource-repo-status
    params: { state: "pending", description: "STARTED job-unit-tests in concourse ci.", commit: "gce-instance-resource" }
  - task: task-unit-tests
    file: gce-instance-resource/ci/tasks/task-unit-tests.yml
    on_success:
      do:
      - put: gce-instance-resource
        params:
          repository: gce-instance-resource  
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text_file: coverage-results/test_coverage.txt
          text: |
            From gce-instance-resource: PASSED job-unit-tests in concourse ci. 
            $TEXT_FILE_CONTENT
      - put: resource-repo-status
        params: { state: "success", description: "PASSED job-unit-tests in concourse ci", commit: "gce-instance-resource" }
    on_failure:
      do:
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From gce-instance-resource: FAILED job-unit-tests in concourse ci."
      - put: resource-repo-status
        params: { state: "failure", description: "FAILED job-unit-tests in concourse ci.", commit: "gce-instance-resource" }

- name: job-build
  plan:
    - get: gce-instance-resource
      trigger: true
      passed: [job-unit-tests]
    - put: resource-slack-alert
      params:
        channel: '#jeff-builds'
        text: "From gce-instance-resource: STARTED job-build in concourse ci."
    - put: resource-repo-status
      params: { state: "pending", description: "STARTED job-build in concourse ci.", commit: "gce-instance-resource" }
    - task: task-build
      file: gce-instance-resource/ci/tasks/task-build.yml
    - put: resource-dump-to-dockerhub
      params: { build: "dist"}
    - put: resource-template
      params: { param1: "Hello Jeff", param2: "How are you?" }    
      on_success:
        do:
        - put: resource-slack-alert
          params:
            channel: '#jeff-builds'
            text: "From gce-instance-resource: PASSED job-build in concourse ci."
        - put: resource-repo-status
          params: { state: "pending", description: "PASSED job-build in concourse ci.", commit: "gce-instance-resource" }
      on_failure:
        do:
        - put: resource-slack-alert
          params:
            channel: '#jeff-builds'
            text: "From gce-instance-resource: FAILED job-build in concourse ci."
        - put: resource-repo-status
          params: { state: "failure", description: "FAILED job-build in concourse ci.", commit: "gce-instance-resource" }
    
resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master
- name: jeffs-resource
  type: docker-image
  source:
   repository: jeffdecola/resource-template
   tag: latest

resources:

- name: gce-instance-resource
  type: git
  source:
    #uri: https://github.com/jeffdecola/gce-instance-resource
    uri: git@github.com:jeffdecola/gce-instance-resource.git
    branch: master
    private_key: {{git_private_key}}
- name: resource-dump-to-dockerhub
  type: docker-image
  source:
    repository: jeffdecola/gce-instance-resource
    tag: latest
    username: jeffdecola
    password: {{dockerhub_password}}
- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}} 
- name: resource-repo-status 
  type: github-status
  source:
    repository: jeffdecola/gce-instance-resource 
    access_token: {{repo_github_token}}
- name: resource-template
  type: jeffs-resource
  source:
    source1: sourcefoo1 
    source2: sourcefoo2
